# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fd62437b045b8090991f82b30b951f356ab52815ac1d761ffdbea28395b9e77c7396251256b9608b6fd253973ae6871ba53ab00076e69d1392bb47cf01d2f8a

test:
  secret_key_base: 13264eff3942046f489bf341488d29528f6ebd8f8fab2bd0f6eed36b9138976e57c702a33ca97cc593cc3f3b07e441e70f91764b9b349f7296bff0419d02aa25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
